packages:
  - "nuxt"
  - "nuxt/*"
  - "react"
  - "react/*"
  - "svelte"
  - "svelte/*"
  - "tanstack"
  - "tanstack/*"
  - "vue"
  - "vue/*"

catalog:
  "@module-federation/vite": "https://pkg.pr.new/@module-federation/vite@472"
