packages:
  - "{angular,nuxt,react,solid,svelte,tanstack,vinext,vue}"
  - "{angular,nuxt,react,solid,svelte,tanstack,vinext,vue}/*"

catalog:
  "@module-federation/vite": "https://pkg.pr.new/@module-federation/vite@559"
